/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import pro.Manager;

/**
 *
 * @author LAPTOP1
 */
public class managerAdminJF extends javax.swing.JInternalFrame {

    /**
     * Creates new form managerAdminJF
     */
    public managerAdminJF() {
        initComponents();
        refresh();
    }

    public void addRows()
    {
        DefaultTableModel model = (DefaultTableModel) mLIST.getModel();
        Object rowData[] =new Object[7];
        Manager s=new Manager();
        ArrayList<Manager> sl=new ArrayList<>();
        sl=(ArrayList<Manager>) s.listMember();
        for (Manager x:sl)
        {
            rowData[0]=x.getFirstName();
            rowData[1]=x.getLastName();
            rowData[2]=x.getUserName();
            rowData[3]=x.getPassword();
            rowData[4]=x.getId();
            rowData[5]=x.getSalary();
            rowData[6]=x.getAge();
            model.addRow(rowData);
        }
    }
    public void refresh()
    {
        DefaultTableModel doList = (DefaultTableModel) mLIST.getModel();
        int rowCount = mLIST.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
         doList.removeRow(i);
        }
        addRows();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mLIST = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        mFN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        mLN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        mUN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        mPASS = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        mID = new javax.swing.JTextField();
        mUPDATE = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        mSALARY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        mAGE = new javax.swing.JTextField();
        mSEARCH = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        mIDSEARCH = new javax.swing.JTextField();
        mREMOVE = new javax.swing.JButton();
        mADD = new javax.swing.JButton();

        mLIST.setBackground(new java.awt.Color(97, 212, 195));
        mLIST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "User Name", "Password", "Id", "Salary", "Age"
            }
        ));
        mLIST.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                mLISTComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(mLIST);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGER");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIRST NAME");

        mFN.setBackground(new java.awt.Color(97, 212, 195));
        mFN.setForeground(new java.awt.Color(255, 255, 255));
        mFN.setText("Enter First Name");
        mFN.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LAST NAME");

        mLN.setBackground(new java.awt.Color(97, 212, 195));
        mLN.setForeground(new java.awt.Color(255, 255, 255));
        mLN.setText("Enter Last Name");
        mLN.setBorder(null);
        mLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME");

        mUN.setBackground(new java.awt.Color(97, 212, 195));
        mUN.setForeground(new java.awt.Color(255, 255, 255));
        mUN.setText("Enter UserName");
        mUN.setBorder(null);
        mUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");

        mPASS.setBackground(new java.awt.Color(97, 212, 195));
        mPASS.setForeground(new java.awt.Color(255, 255, 255));
        mPASS.setText("jPasswordField1");
        mPASS.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");

        mID.setBackground(new java.awt.Color(97, 212, 195));
        mID.setForeground(new java.awt.Color(255, 255, 255));
        mID.setText("Enter User id");
        mID.setBorder(null);
        mID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIDActionPerformed(evt);
            }
        });

        mUPDATE.setBackground(new java.awt.Color(0, 0, 0));
        mUPDATE.setForeground(new java.awt.Color(255, 255, 255));
        mUPDATE.setText("UPDATE");
        mUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mUPDATEActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SALARY");

        mSALARY.setBackground(new java.awt.Color(97, 212, 195));
        mSALARY.setForeground(new java.awt.Color(255, 255, 255));
        mSALARY.setText("Enter Salary");
        mSALARY.setBorder(null);
        mSALARY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSALARYActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AGE");

        mAGE.setBackground(new java.awt.Color(97, 212, 195));
        mAGE.setForeground(new java.awt.Color(255, 255, 255));
        mAGE.setText("Enter Age");
        mAGE.setBorder(null);
        mAGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAGEActionPerformed(evt);
            }
        });

        mSEARCH.setBackground(new java.awt.Color(0, 0, 0));
        mSEARCH.setForeground(new java.awt.Color(255, 255, 255));
        mSEARCH.setText("SEARCH");
        mSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSEARCHActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ID");

        mIDSEARCH.setBackground(new java.awt.Color(97, 212, 195));
        mIDSEARCH.setForeground(new java.awt.Color(255, 255, 255));
        mIDSEARCH.setText("Enter User id");
        mIDSEARCH.setBorder(null);
        mIDSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIDSEARCHActionPerformed(evt);
            }
        });

        mREMOVE.setBackground(new java.awt.Color(0, 0, 0));
        mREMOVE.setForeground(new java.awt.Color(255, 255, 255));
        mREMOVE.setText("REMOVE");
        mREMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mREMOVEActionPerformed(evt);
            }
        });

        mADD.setBackground(new java.awt.Color(0, 0, 0));
        mADD.setForeground(new java.awt.Color(255, 255, 255));
        mADD.setText("ADD SELLER");
        mADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mADDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(mUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mADD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mREMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(mAGE)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator19)
                                    .addComponent(mIDSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(mSEARCH))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mLN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mFN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                .addComponent(mPASS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mUN, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(mSALARY, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mIDSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mFN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mLN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mUN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(mPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addComponent(mSALARY, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(mAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mADD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mREMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mLNActionPerformed

    private void mUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mUNActionPerformed

    private void mIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mIDActionPerformed

    private void mUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mUPDATEActionPerformed
        // TODO add your handling code here:
        Manager s=new Manager(Integer.parseInt(mAGE.getText()),Double.parseDouble(mSALARY.getText()),mFN.getText(),mLN.getText(),mPASS.getText(),Integer.parseInt(mID.getText()),mUN.getText());
        s.updateMember();
        refresh();
    }//GEN-LAST:event_mUPDATEActionPerformed

    private void mSALARYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSALARYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mSALARYActionPerformed

    private void mAGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mAGEActionPerformed

    private void mSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSEARCHActionPerformed
        // TODO add your handling code here:
        Manager s=new Manager();
        Manager tmp=new Manager();
        tmp=(Manager) s.searchMember(Integer.parseInt(mIDSEARCH.getText()));
        mAGE.setText(tmp.getAge()+"");
        mFN.setText(tmp.getFirstName());
        mLN.setText(tmp.getLastName());
        mPASS.setText(tmp.getPassword());
        mUN.setText(tmp.getUserName());
        mID.setText(tmp.getId()+"");
        mSALARY.setText(tmp.getSalary()+"");
    }//GEN-LAST:event_mSEARCHActionPerformed

    private void mIDSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIDSEARCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mIDSEARCHActionPerformed

    private void mREMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mREMOVEActionPerformed
        // TODO add your handling code here:
        Manager s=new Manager();
        s.deleteMember(Integer.parseInt(mID.getText()));
        refresh();
    }//GEN-LAST:event_mREMOVEActionPerformed

    private void mADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mADDActionPerformed
        // TODO add your handling code here:
        //    public Seller(int age, double salary, String firstName, String lastName, String password, int id, String userName) {
            if (!mAGE.getText().equals("")&&!mSALARY.getText().equals("")&&!mFN.getText().equals("")&&!mLN.getText().equals("")&&!mPASS.getText().equals("")&&!mID.getText().equals("")&&!mUN.getText().equals(""))
            {
                Manager s=new Manager(Integer.parseInt(mAGE.getText()),Double.parseDouble(mSALARY.getText()),mFN.getText(),mLN.getText(),mPASS.getText(),Integer.parseInt(mID.getText()),mUN.getText());
                s.addMember();
            }
            refresh();
    }//GEN-LAST:event_mADDActionPerformed

    private void mLISTComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_mLISTComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_mLISTComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton mADD;
    private javax.swing.JTextField mAGE;
    private javax.swing.JTextField mFN;
    private javax.swing.JTextField mID;
    private javax.swing.JTextField mIDSEARCH;
    private javax.swing.JTable mLIST;
    private javax.swing.JTextField mLN;
    private javax.swing.JPasswordField mPASS;
    private javax.swing.JButton mREMOVE;
    private javax.swing.JTextField mSALARY;
    private javax.swing.JButton mSEARCH;
    private javax.swing.JTextField mUN;
    private javax.swing.JButton mUPDATE;
    // End of variables declaration//GEN-END:variables
}
