/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import pro.Order;
import pro.Product;

/**
 *
 * @author LAPTOP1
 */
public class ordersJF extends javax.swing.JInternalFrame {

    /**
     * Creates new form ordersJF
     */
    public ordersJF() {
        initComponents();
        addOrdersRows();
    }

    public void addOrdersRows() {

        DefaultTableModel model = (DefaultTableModel) indexTable1.getModel();
        Object rowData[] = new Object[1];
        Product s = new Product();
        Order o = new Order();
        ArrayList<ArrayList<Product>> x = o.list();
        ArrayList<ArrayList<ArrayList<Product>>> m = new ArrayList<>();

        for (int i = 0; i < x.size(); i++) {
            rowData[0] = i;
            model.addRow(rowData);
        }
    }

    public void refresh() {
        DefaultTableModel doList = (DefaultTableModel) oLIST.getModel();
        int rowCount = doList.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            doList.removeRow(i);
        }
        DefaultTableModel dpList = (DefaultTableModel) oLIST.getModel();
        rowCount = dpList.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            dpList.removeRow(i);
        }
        addProductRows(indexTable1.getSelectedRow());

    }

    public void addProductRows(int index) {
        DefaultTableModel model = (DefaultTableModel) oLIST.getModel();
        Object rowData[] = new Object[4];
        Product s = new Product();
        Order o = new Order();
        ArrayList<ArrayList<Product>> x = o.list();
        ArrayList<Product> m = x.get(index);
        for (Product z : m) {

            rowData[1] = z.getId();
            rowData[0] = z.getName();
            rowData[2] = z.getQuantity();
            rowData[3] = z.getPrice();
            model.addRow(rowData);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        oLIST = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        indexTable1 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jButton1.setText("show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        oLIST.setBackground(new java.awt.Color(97, 212, 195));
        oLIST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "id", "quantity", "price"
            }
        ));
        oLIST.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                oLISTAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(oLIST);

        indexTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "index"
            }
        ));
        jScrollPane2.setViewportView(indexTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oLISTAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_oLISTAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_oLISTAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable indexTable1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable oLIST;
    // End of variables declaration//GEN-END:variables
}
