/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.objects.NativeString;
import pro.Seller;

/**
 *
 * @author LAPTOP1
 */
public class sellerAdminJF extends javax.swing.JInternalFrame {

    /**
     * Creates new form sellerAdminJF
     */
    
    public sellerAdminJF() {
        initComponents();
        refresh();
    }
    
    // to fill field
    public void addRows()
    {
        DefaultTableModel model = (DefaultTableModel) sLIST.getModel();
        Object rowData[] =new Object[7];
        Seller s=new Seller();
        ArrayList<Seller> sl=new ArrayList<>();
        sl=(ArrayList<Seller>) s.listMember();
        for (Seller x:sl)
        {
            rowData[0]=x.getFirstName();
            rowData[1]=x.getLastName();
            rowData[2]=x.getUserName();
            rowData[3]=x.getPassword();
            rowData[4]=x.getId();
            rowData[5]=x.getSalary();
            rowData[6]=x.getAge();
            model.addRow(rowData);
        }
    }
    
    // to set data in text fields 
    public void update(int id)
    {
        Seller s=new Seller();
        Seller tmp=new Seller();
        tmp=(Seller) s.searchMember(id);
        sAGE.setText(tmp.getAge()+"");
        sFN.setText(tmp.getFirstName());
        sLN.setText(tmp.getLastName());
        sPASS.setText(tmp.getPassword());
        sUN.setText(tmp.getUserName());
        sID.setText(tmp.getId()+"");
        sSALARY.setText(tmp.getSalary()+"");
    }
    
    //  remove element from table and fill it with new element
    public void refresh()
    {
        DefaultTableModel doList = (DefaultTableModel) sLIST.getModel();
        int rowCount = sLIST.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
         doList.removeRow(i);
        }
        addRows();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sFN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        sLN = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        sUN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        sPASS = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        sID = new javax.swing.JTextField();
        sUPDATE = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        sSALARY = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        sAGE = new javax.swing.JTextField();
        sSEARCH = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        sIDSEARCH = new javax.swing.JTextField();
        sREMOVE = new javax.swing.JButton();
        sADD = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sLIST = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELLER");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FIRST NAME");

        sFN.setBackground(new java.awt.Color(97, 212, 195));
        sFN.setForeground(new java.awt.Color(255, 255, 255));
        sFN.setText("Enter First Name");
        sFN.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LAST NAME");

        sLN.setBackground(new java.awt.Color(97, 212, 195));
        sLN.setForeground(new java.awt.Color(255, 255, 255));
        sLN.setText("Enter Last Name");
        sLN.setBorder(null);
        sLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sLNActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("USERNAME");

        sUN.setBackground(new java.awt.Color(97, 212, 195));
        sUN.setForeground(new java.awt.Color(255, 255, 255));
        sUN.setText("Enter UserName");
        sUN.setBorder(null);
        sUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUNActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");

        sPASS.setBackground(new java.awt.Color(97, 212, 195));
        sPASS.setForeground(new java.awt.Color(255, 255, 255));
        sPASS.setText("jPasswordField1");
        sPASS.setBorder(null);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID");

        sID.setBackground(new java.awt.Color(97, 212, 195));
        sID.setForeground(new java.awt.Color(255, 255, 255));
        sID.setText("Enter User id");
        sID.setBorder(null);
        sID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sIDActionPerformed(evt);
            }
        });

        sUPDATE.setBackground(new java.awt.Color(0, 0, 0));
        sUPDATE.setForeground(new java.awt.Color(255, 255, 255));
        sUPDATE.setText("UPDATE");
        sUPDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUPDATEActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SALARY");

        sSALARY.setBackground(new java.awt.Color(97, 212, 195));
        sSALARY.setForeground(new java.awt.Color(255, 255, 255));
        sSALARY.setText("Enter Salary");
        sSALARY.setBorder(null);
        sSALARY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSALARYActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AGE");

        sAGE.setBackground(new java.awt.Color(97, 212, 195));
        sAGE.setForeground(new java.awt.Color(255, 255, 255));
        sAGE.setText("Enter Age");
        sAGE.setBorder(null);
        sAGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sAGEActionPerformed(evt);
            }
        });

        sSEARCH.setBackground(new java.awt.Color(0, 0, 0));
        sSEARCH.setForeground(new java.awt.Color(255, 255, 255));
        sSEARCH.setText("SEARCH");
        sSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sSEARCHActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ID");

        sIDSEARCH.setBackground(new java.awt.Color(97, 212, 195));
        sIDSEARCH.setForeground(new java.awt.Color(255, 255, 255));
        sIDSEARCH.setText("Enter User id");
        sIDSEARCH.setBorder(null);
        sIDSEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sIDSEARCHActionPerformed(evt);
            }
        });

        sREMOVE.setBackground(new java.awt.Color(0, 0, 0));
        sREMOVE.setForeground(new java.awt.Color(255, 255, 255));
        sREMOVE.setText("REMOVE");
        sREMOVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sREMOVEActionPerformed(evt);
            }
        });

        sADD.setBackground(new java.awt.Color(0, 0, 0));
        sADD.setForeground(new java.awt.Color(255, 255, 255));
        sADD.setText("ADD SELLER");
        sADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sADDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sADD, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sREMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(sAGE)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(sSALARY, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator19)
                                    .addComponent(sIDSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(sSEARCH))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sLN, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sFN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                                .addComponent(sPASS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sUN, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sIDSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sSEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(jSeparator19, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sFN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sLN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sUN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addGap(9, 9, 9)
                .addComponent(sPASS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addGap(7, 7, 7)
                .addComponent(sSALARY, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(sAGE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sUPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sADD, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sREMOVE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        sLIST.setBackground(new java.awt.Color(97, 212, 195));
        sLIST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "User Name", "Password", "Id", "Salary", "Age"
            }
        ));
        sLIST.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                sLISTComponentAdded(evt);
            }
        });
        jScrollPane1.setViewportView(sLIST);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sLNActionPerformed

    private void sUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sUNActionPerformed

    private void sIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sIDActionPerformed

    private void sSALARYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSALARYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sSALARYActionPerformed

    private void sAGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sAGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sAGEActionPerformed

    private void sIDSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sIDSEARCHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sIDSEARCHActionPerformed

    private void sADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sADDActionPerformed
        // TODO add your handling code here:
        //    public Seller(int age, double salary, String firstName, String lastName, String password, int id, String userName) {
        if (!sAGE.getText().equals("")&&!sSALARY.getText().equals("")&&!sFN.getText().equals("")&&!sLN.getText().equals("")&&!sPASS.getText().equals("")&&!sID.getText().equals("")&&!sUN.getText().equals(""))
        {
        Seller s=new Seller(Integer.parseInt(sAGE.getText()),Double.parseDouble(sSALARY.getText()),sFN.getText(),sLN.getText(),sPASS.getText(),Integer.parseInt(sID.getText()),sUN.getText());
        s.addMember(); 
        }
        refresh();
    }//GEN-LAST:event_sADDActionPerformed

    private void sSEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sSEARCHActionPerformed
        // TODO add your handling code here:
        Seller s=new Seller();
        Seller tmp=new Seller();
        tmp=(Seller) s.searchMember(Integer.parseInt(sIDSEARCH.getText()));
        sAGE.setText(tmp.getAge()+"");
        sFN.setText(tmp.getFirstName());
        sLN.setText(tmp.getLastName());
        sPASS.setText(tmp.getPassword());
        sUN.setText(tmp.getUserName());
        sID.setText(tmp.getId()+"");
        sSALARY.setText(tmp.getSalary()+"");
    }//GEN-LAST:event_sSEARCHActionPerformed

    private void sUPDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUPDATEActionPerformed
        // TODO add your handling code here:
        Seller s=new Seller(Integer.parseInt(sAGE.getText()),Double.parseDouble(sSALARY.getText()),sFN.getText(),sLN.getText(),sPASS.getText(),Integer.parseInt(sID.getText()),sUN.getText());
        s.updateMember();
        refresh();
        update(s.getId());
    
        
    }//GEN-LAST:event_sUPDATEActionPerformed

    private void sREMOVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sREMOVEActionPerformed
        // TODO add your handling code here:
        Seller s=new Seller();
        s.deleteMember(Integer.parseInt(sID.getText()));
        refresh();
    }//GEN-LAST:event_sREMOVEActionPerformed

    private void sLISTComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_sLISTComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_sLISTComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JButton sADD;
    private javax.swing.JTextField sAGE;
    private javax.swing.JTextField sFN;
    private javax.swing.JTextField sID;
    private javax.swing.JTextField sIDSEARCH;
    private javax.swing.JTable sLIST;
    private javax.swing.JTextField sLN;
    private javax.swing.JPasswordField sPASS;
    private javax.swing.JButton sREMOVE;
    private javax.swing.JTextField sSALARY;
    private javax.swing.JButton sSEARCH;
    private javax.swing.JTextField sUN;
    private javax.swing.JButton sUPDATE;
    // End of variables declaration//GEN-END:variables
}
